### ISSUE TITLE
Memory Leaks when running or trying to Generate Tile Map

### ISSUE THREAD

**Issue by mwikala** [dariowouters/ts-map#12]
Sometimes when just dragging around the generated map, I get a crash with error `System out of memory` on the Memory Chart, it constantly just keeps increasing from the second the project is running.

Video [here](https://streamable.com/tz4wxk)

Any suggestions on how I can get this running?

`EDIT:

Print out of the exception;
```
System.OutOfMemoryException
  HResult=0x8007000E
  Message=Out of memory.
  Source=System.Drawing
  StackTrace:
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawCurve(Pen pen, PointF[] points)
   at TsMap.TsMapRenderer.Render(Graphics g, Rectangle clip, Single scale, PointF startPoint, MapPalette palette, RenderFlags renderFlags) in C:\Users\kangw\Documents\ts-map\TsMap\TsMapRenderer.cs:line 374
   at TsMap.Canvas.TsMapCanvas.SaveTileImage(Int32 z, Int32 x, Int32 y, PointF pos, Single zoom, String exportPath) in C:\Users\kangw\Documents\ts-map\TsMap.Canvas\TsMapCanvas.cs:line 100
   at TsMap.Canvas.TsMapCanvas.GenerateTileMap(Int32 zoomLevel, String exportPath) in C:\Users\kangw\Documents\ts-map\TsMap.Canvas\TsMapCanvas.cs:line 139
   at TsMap.Canvas.TsMapCanvas.<GenerateTileMapToolStripMenuItem_Click>b__25_0(Int32 zoomLevel) in C:\Users\kangw\Documents\ts-map\TsMap.Canvas\TsMapCanvas.cs:line 215
   at TsMap.Canvas.TileMapGeneratorForm.GenerateBtn_Click(Object sender, EventArgs e) in C:\Users\kangw\Documents\ts-map\TsMap.Canvas\TileMapGeneratorForm.cs:line 18
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at TsMap.Canvas.Program.Main() in C:\Users\kangw\Documents\ts-map\TsMap.Canvas\Program.cs:line 16

  This exception was originally thrown at this call stack:
    [External Code]
    TsMap.TsMapRenderer.Render(System.Drawing.Graphics, System.Drawing.Rectangle, float, System.Drawing.PointF, TsMap.MapPalette, TsMap.RenderFlags) in TsMapRenderer.cs
    TsMap.Canvas.TsMapCanvas.SaveTileImage(int, int, int, System.Drawing.PointF, float, string) in TsMapCanvas.cs
    TsMap.Canvas.TsMapCanvas.GenerateTileMap(int, string) in TsMapCanvas.cs
    TsMap.Canvas.TsMapCanvas.GenerateTileMapToolStripMenuItem_Click.AnonymousMethod__25_0(int) in TsMapCanvas.cs
    TsMap.Canvas.TileMapGeneratorForm.GenerateBtn_Click(object, System.EventArgs) in TileMapGeneratorForm.cs
    [External Code]
    TsMap.Canvas.Program.Main() in Program.cs
```

**Comment by AleksaDjordjic** [comment]
This is a problem with GDI+, and errors from it usually don't give much info...
I doubt its actually out of memory, had a lot of stuff crash with that error where the cause was not it running out of memory instead it was me giving it wrong data that it couldn't work with.

Its something messed up in the Turkey area I think, specifically on zoom level 2.
Download the new update and use it to generate the tilemap from level 3 onward, you will miss 0, 1 and 2 but it is what it is for now. You can generate 0-1 later on, but 2 specifically is broken.

I wasn't able to see what was wrong with it, and I'm debugging it for quite a while now

Not a fix, but a potentially useful workaround

**Comment by mwikala** [comment]
Great stuff, thank you for that. That's more info than I had about the issue, I knew it couldn't be a memory issue. Currently running 1.38 and still had the issue but I'll try just generating from Level 3 upwards.

**Comment by shardick** [comment]
it's an old problem, it's related on how tiles are generated but I think it didn't happen on previous version because I generated 1.37 from 0 to 8.

I'm curious, how you are using the generated tiles? with leaflet? have a custom tracker to show your vtc members driving around or something?

**Comment by AleksaDjordjic** [comment]
If needed, this is a specific point and scale configuration that breaks it
If you don't scale the transform, it works fine, if you do, it shows an out of memory exception, maybe its something with float precision?
Also, note, this is at the "Road to the Black Sea" DLC part of the map
Maybe map reaches too far out that floats just jerk out and break everything like they do...

`private void Form1_Paint(object sender, PaintEventArgs e)
{
    e.Graphics.ScaleTransform(0.00358749786f, 0.00358749786f);

    var pen = new Pen(Brushes.Gray, 493);
    var points = new PointF[]
    {
        new PointF
        {
            X = 56571.0547f,
            Y = 29761.39f,
        },
        new PointF
        {
            X = 56572.4648f,
            Y = 29761.498f,
        },
        new PointF
        {
            X = 56573.875f,
            Y = 29761.6074f,
        },
        new PointF
        {
            X = 56575.2852f,
            Y = 29761.7148f,
        },
        new PointF
        {
            X = 56576.7f,
            Y = 29761.8242f,
        },
        new PointF
        {
            X = 56578.11f,
            Y = 29761.9316f,
        },
        new PointF
        {
            X = 56579.52f,
            Y = 29762.041f,
        },
        new PointF
        {
            X = 56580.93f,
            Y = 29762.1484f,
        },
    };

    e.Graphics.DrawCurve(pen, points);
}`

**Comment by AleksaDjordjic** [comment]
Also, with a new update now, I don't remember where it was but not level 1 is broken for me too... It was fine before

**Comment by AleksaDjordjic** [comment]
One fix is to put it in a try catch on line 336, this will make it avoid drawing some roads that fail, but honestly at those levels its barely noticeable, I couldn't find a missing road
![image](https://user-images.githubusercontent.com/33227154/89303322-56d78b80-d66c-11ea-9e1f-0223caeadd37.png)
Here is the result
![1](https://user-images.githubusercontent.com/33227154/89303341-5e973000-d66c-11ea-93a5-cf8572eeb2e2.png)

**Comment by DubStepMad** [comment]
@AleksaDjordjic The try catch seems the best work around for now as I implemented this and it only seems to be affecting a few roads as I ended up outputting the system error.

However I am also using the promods mods while extracting the map.

**Comment by dariowouters** [comment]
@DubStepMad The latest update in the develop branch should fix that issue, and possibly also just this issue in general.

This was because in Belgium (where I live) we use a comma ( , ) as a decimal notation and forgot that that is not the case everywhere. So whenever I would read a value from a file I replaced the dot ( . ) decimal notation with a comma. This caused values to be read completely wrong whenever the locale settings on your computer do not use a comma decimal notation.

**Comment by DubStepMad** [comment]
@dariowouters Can confirm it completly solves the issue. Thank you.
